language: "node_js"
node_js: "stable"
sudo: false
before_script:
  - "npm run build"
  - "gzip < public/browser.js > public/browser.js.gz"
  - "du -hc public/*"
  - "npm run start 2>&1 > http.log &"
  - "sleep 3"
  - "npm run phantom 2>&1 > phantom.log &"
  - "sleep 3"
after_script:
  - "cat http.log"
  - "cat phantom.log"
